### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by IMS212** [Kerberus-MC/Flourish#1]
I cannot legally stop you from doing this, however I would like to know a few things.

- Is there a specific issue you have with Iris that requires a fork? We have a Discord and it specifically asks if you can ask permission to re-release versions of Iris.
- What sort of "new features for the community" will this fork have? I don't see it.

**Comment by KerberusGG** [comment]
We would like to have iris on curseforge and not have to switch over to modrinth just because of someone's personal opinions of curseforge. Since this is open source we plan on having a alternative for us and other modder's within the community who don't want to be forced to switch over just yet as modrinth is relatively new and needs to have a more sustained revenue source before having us commit to this move. 

If this is something you don't support, your license/github page should specify that. The features for the community that we plan to bring our own and we don't plan on disclosing it till it is officially released.

**Comment by IMS212** [comment]
Very well. These aren't personal opinions of CurseForge, however, rather core problems with the platform that we believe affect everyone. 

The core issue with CurseForge's recent actions is not only did they engage in bad business practices, but after they left they *explicitly* changed the rules to allow this sort of mods.

To be clear, Iris is still allowed, and doesn't plan to ever disallow, being added as an external mod in CurseForge modpacks. The move to Modrinth should not affect modpack makers. 

By releasing a fork of Iris with no new features as of now, you are essentially cloning Iris for CurseForge revenue when it would be perfectly legal and preferred to use the official version. I highly recommend not releasing anything until you do have these new features in place, for this reason.

**Comment by KerberusGG** [comment]
as mentioned on our page and on the source, we do not claim any revenue for this project and actually even have it allowed for third party platforms. I agree with the problems with the site but harming modder's is not the way of doing this. You could have gone the modmenu route, kept your existing files up and not updated the page anymore. Continued the project on modrinth with a direct link to it for updates. 

If you left/reuploaded the versions for iris, we wouldn't be in a position where we have to repackage and upload them as a fork. We are not taking revenue/donations, nor do we plan to monetize this ever. We will be updating iris till a better alternative comes along and we don't have to. You are still credited in the page and all links lead to your website https://irisshaders.net. As you mention, if people want to use it they will still be able to add it in their packs as a external mod, our fork does not impact iris in any way other than provide it on a platform and allow creators the right to free will and choosing their platforms.

We don't want to add the mod as a override mod/externally since we prefer to having the mod to be easily accessible, even for newbie modders who are new to the space.
